name: On TileBoard Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Newly released TileBoard version
        required: true
      release_url:
        description: The URL of the TileBoard release
        required: true

jobs:
  build-addon:
    name: Bump TileBoard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # with tags

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: yarn install

      - name: Update version
        run: |
          git config --local user.email "invalid@email.com"
          git config --local user.name "Autorelease"
          jq  '.args.TILEBOARD_VERSION = "${{ github.event.inputs.version }}"' addon/build.json > addon/build_new.json
          mv addon/build_new.json addon/build.json
          git add ./addon/build.json
          git commit -m 'chore: bump TileBoard version to v${{ github.event.inputs.version }}'

      - name: Create release
        run: yarn release

      # Publish the addon. This needs to be repeated in this workflow as pushing a new tag from a workflow
      # won't trigger the on_push workflow.

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ./addon \
            --docker-hub tileboard
