name: On TileBoard Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Newly released TileBoard version
        required: true
      release_url:
        description: The URL of the TileBoard release
        required: true

jobs:
  build-addon:
    name: Build Add-on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # with tags

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: yarn install

      - name: Update version
        run: |
          git config --local user.email "invalid@email.com"
          git config --local user.name "Autorelease"
          sed -i -E 's/("version"): "[^"]+"/\1: "${{ github.event.inputs.version }}"/' ./addon/config.json
          git add ./addon/config.json
          git commit -m 'chore: bump TileBoard version to "${{ github.event.inputs.version }}"'
          yarn changelog --latest-version ${{ github.event.inputs.version }}
          git add ./addon/CHANGELOG.md
          git commit -m 'chore(release): ${{ github.event.inputs.version }}'
          git tag ${{ github.event.inputs.version }}
          git push --tags
          git push

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ./addon \
            --docker-hub tileboard
